server:
  error:
    include-message: always
    include-binding-errors: always
  port : 8080

spring:
  datasource:
    password: JOB_SWITCH
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: JOB_SWITCH
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        format_sql: true
    show-sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
